### ISSUE TITLE
class DS3231' has no member named 'getTime'

### ISSUE THREAD

**Issue by raghavnpa** [drolsen/DRO-Matic#131]
Dear sir,

I am trying to compile in Arduion IDE 1.8.4 , getting error " class DS3231' has no member named 'getTime' ". Please specify which library to be used for DS3231.

Thank u
